// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calib
Rcpp::List calib(arma::vec theta1, arma::mat theta2, arma::vec theta, int n, int p, int B1, int B2, double B10, double B20);
RcppExport SEXP _GMS_calib(SEXP theta1SEXP, SEXP theta2SEXP, SEXP thetaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B10SEXP, SEXP B20SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< int >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< double >::type B10(B10SEXP);
    Rcpp::traits::input_parameter< double >::type B20(B20SEXP);
    rcpp_result_gen = Rcpp::wrap(calib(theta1, theta2, theta, n, p, B1, B2, B10, B20));
    return rcpp_result_gen;
END_RCPP
}
// calib_new
Rcpp::List calib_new(arma::vec theta1, arma::mat theta2, arma::vec theta, int n, int p, int B1, int B2, double B10, double B20);
RcppExport SEXP _GMS_calib_new(SEXP theta1SEXP, SEXP theta2SEXP, SEXP thetaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B10SEXP, SEXP B20SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< int >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< double >::type B10(B10SEXP);
    Rcpp::traits::input_parameter< double >::type B20(B20SEXP);
    rcpp_result_gen = Rcpp::wrap(calib_new(theta1, theta2, theta, n, p, B1, B2, B10, B20));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GMS_calib", (DL_FUNC) &_GMS_calib, 9},
    {"_GMS_calib_new", (DL_FUNC) &_GMS_calib_new, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_GMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
