# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calib <- function(theta1, theta2, theta, n, p, B1, B2, B10, B20) {
    .Call(`_GMS_calib`, theta1, theta2, theta, n, p, B1, B2, B10, B20)
}

calib_new <- function(theta1, theta2, theta, n, p, B1, B2, B10, B20) {
    .Call(`_GMS_calib_new`, theta1, theta2, theta, n, p, B1, B2, B10, B20)
}

